### PR TITLE
Fix build on centos7 gcc4.8

### LINKED ISSUE #2491: Fix compile on CentOS7 gcc4.8.5
**Environment information**
* Operating System: CentOS7 x86_64
* Cutter version: master branch
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**
compile error on CentOS7 with gcc4.8.5

**To Reproduce**

1. follow the build instruction

**Expected behavior**
build without error

https://stackoverflow.com/questions/30402943/has-cpp-attribute-not-a-function-like-macro
```
cutter/src/core/CutterCommon.h:65:56: error: missing binary operator before token "("
 #if defined(__has_cpp_attribute) && __has_cpp_attribute(deprecated)
                                                        ^
gmake[2]: *** [CMakeFiles/Cutter.dir/Cutter_autogen/mocs_compilation.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Cutter.dir/all] Error 2
gmake: *** [all] Error 2
```
this can be fixed as
```
#if defined(__has_cpp_attribute)
    #if __has_cpp_attribute(deprecated)
        #define DEPRECATED(msg) [[deprecated(msg)]]
    #endif
#else
#define CUTTER_DEPRECATED(msg)
#endif
```

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by biyuhao**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://cutter.re/docs/contributing/code/getting-started.html) to this repository
- [x] I made sure to follow the project's [coding style](https://cutter.re/docs/contributing/code/development-guidelines.html)
- [x] I've updated the [documentation](https://cutter.re/docs/user-docs.html) with the relevant information (if needed)

**Detailed description**

Fix compile error on CentOS7
**Test plan (required)**

build on CentOS7 & gcc4.8.5

**Closing issues**
closes #2491

### CODE REVIEW

**Review by karliss — CHANGES_REQUESTED** [review]
This will fail in case `__has_cpp_attribute` is defined but the `deprecated` attribute isn't available. You need to add one more else case or change the else to `#if !defined(CUTTER_DEPRECATED)`.

**Review by ITAYC0HEN — APPROVED** [review]
Looks good! Thank you :)

**Review by karliss — APPROVED** [review]
