### ISSUE TITLE
R_EVENT issues preventing building

### ISSUE THREAD

**Issue by philipmnelson** [radareorg/cutter#1173]
**Environment information**
* Operating System: Arch Linux 
* Cutter version: Git 

**Describe the bug**
Cannot build Cutter, 
```
../src/Cutter.cpp: In constructor ‘CutterCore::CutterCore(QObject*)’:
../src/Cutter.cpp:146:74: error: too many arguments to function ‘void r_event_hook(REvent*, int, REventCallback)’
     r_event_hook(core_->anal->ev, R_EVENT_ALL, cutterREventCallback, this);
                                                                          ^
In file included from /usr/include/libr/r_util.h:27,
                 from /usr/include/libr/r_io.h:7,
                 from /usr/include/libr/r_core.h:9,
                 from ../src/Cutter.h:4,
                 from ../src/common/Configuration.h:6,
                 from ../src/Cutter.cpp:8:
/usr/include/libr/r_util/r_event.h:36:12: note: declared here
 R_API void r_event_hook(REvent *ev, int type, REventCallback cb);
            ^~~~~~~~~~~~
../src/Cutter.cpp: In member function ‘void CutterCore::handleREvent(int, void*)’:
../src/Cutter.cpp:2424:10: error: ‘R_EVENT_CLASS_NEW’ was not declared in this scope
     case R_EVENT_CLASS_NEW: {
          ^~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2424:10: note: suggested alternative: ‘R_EVENT_META_DEL’
     case R_EVENT_CLASS_NEW: {
          ^~~~~~~~~~~~~~~~~
          R_EVENT_META_DEL
../src/Cutter.cpp:2425:36: error: ‘REventClass’ does not name a type; did you mean ‘RBinClass’?
         auto ev = reinterpret_cast<REventClass *>(data);
                                    ^~~~~~~~~~~
                                    RBinClass
../src/Cutter.cpp:2425:48: error: expected ‘>’ before ‘*’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                ^
../src/Cutter.cpp:2425:48: error: expected ‘(’ before ‘*’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                ^
                                                (
../src/Cutter.cpp:2425:49: error: expected primary-expression before ‘>’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                 ^
../src/Cutter.cpp:2425:56: error: expected ‘)’ before ‘;’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                        ^
                                                        )
../src/Cutter.cpp:2429:10: error: ‘R_EVENT_CLASS_DEL’ was not declared in this scope
     case R_EVENT_CLASS_DEL: {
          ^~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2429:10: note: suggested alternative: ‘R_EVENT_META_DEL’
     case R_EVENT_CLASS_DEL: {
          ^~~~~~~~~~~~~~~~~
          R_EVENT_META_DEL
../src/Cutter.cpp:2430:36: error: ‘REventClass’ does not name a type; did you mean ‘RBinClass’?
         auto ev = reinterpret_cast<REventClass *>(data);
                                    ^~~~~~~~~~~
                                    RBinClass
../src/Cutter.cpp:2430:48: error: expected ‘>’ before ‘*’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                ^
../src/Cutter.cpp:2430:48: error: expected ‘(’ before ‘*’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                ^
                                                (
../src/Cutter.cpp:2430:49: error: expected primary-expression before ‘>’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                 ^
../src/Cutter.cpp:2430:56: error: expected ‘)’ before ‘;’ token
         auto ev = reinterpret_cast<REventClass *>(data);
                                                        ^
                                                        )
../src/Cutter.cpp:2434:10: error: ‘R_EVENT_CLASS_RENAME’ was not declared in this scope
     case R_EVENT_CLASS_RENAME: {
          ^~~~~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2434:10: note: suggested alternative: ‘R_BIN_CLASS_PRIVATE’
     case R_EVENT_CLASS_RENAME: {
          ^~~~~~~~~~~~~~~~~~~~
          R_BIN_CLASS_PRIVATE
../src/Cutter.cpp:2435:36: error: ‘REventClassRename’ does not name a type; did you mean ‘REventCallback’?
         auto ev = reinterpret_cast<REventClassRename *>(data);
                                    ^~~~~~~~~~~~~~~~~
                                    REventCallback
../src/Cutter.cpp:2435:54: error: expected ‘>’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassRename *>(data);
                                                      ^
../src/Cutter.cpp:2435:54: error: expected ‘(’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassRename *>(data);
                                                      ^
                                                      (
../src/Cutter.cpp:2435:55: error: expected primary-expression before ‘>’ token
         auto ev = reinterpret_cast<REventClassRename *>(data);
                                                       ^
../src/Cutter.cpp:2435:62: error: expected ‘)’ before ‘;’ token
         auto ev = reinterpret_cast<REventClassRename *>(data);
                                                              ^
                                                              )
../src/Cutter.cpp:2439:10: error: ‘R_EVENT_CLASS_ATTR_SET’ was not declared in this scope
     case R_EVENT_CLASS_ATTR_SET: {
          ^~~~~~~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2439:10: note: suggested alternative: ‘R_EVENT_META_SET’
     case R_EVENT_CLASS_ATTR_SET: {
          ^~~~~~~~~~~~~~~~~~~~~~
          R_EVENT_META_SET
../src/Cutter.cpp:2440:36: error: ‘REventClassAttrSet’ does not name a type
         auto ev = reinterpret_cast<REventClassAttrSet *>(data);
                                    ^~~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2440:55: error: expected ‘>’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassAttrSet *>(data);
                                                       ^
../src/Cutter.cpp:2440:55: error: expected ‘(’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassAttrSet *>(data);
                                                       ^
                                                       (
../src/Cutter.cpp:2440:56: error: expected primary-expression before ‘>’ token
         auto ev = reinterpret_cast<REventClassAttrSet *>(data);
                                                        ^
../src/Cutter.cpp:2440:63: error: expected ‘)’ before ‘;’ token
         auto ev = reinterpret_cast<REventClassAttrSet *>(data);
                                                               ^
                                                               )
../src/Cutter.cpp:2444:10: error: ‘R_EVENT_CLASS_ATTR_DEL’ was not declared in this scope
     case R_EVENT_CLASS_ATTR_DEL: {
          ^~~~~~~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2444:10: note: suggested alternative: ‘R_EVENT_META_DEL’
     case R_EVENT_CLASS_ATTR_DEL: {
          ^~~~~~~~~~~~~~~~~~~~~~
          R_EVENT_META_DEL
../src/Cutter.cpp:2445:36: error: ‘REventClassAttr’ does not name a type; did you mean ‘REventCallback’?
         auto ev = reinterpret_cast<REventClassAttr *>(data);
                                    ^~~~~~~~~~~~~~~
                                    REventCallback
../src/Cutter.cpp:2445:52: error: expected ‘>’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassAttr *>(data);
                                                    ^
../src/Cutter.cpp:2445:52: error: expected ‘(’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassAttr *>(data);
                                                    ^
                                                    (
../src/Cutter.cpp:2445:53: error: expected primary-expression before ‘>’ token
         auto ev = reinterpret_cast<REventClassAttr *>(data);
                                                     ^
../src/Cutter.cpp:2445:60: error: expected ‘)’ before ‘;’ token
         auto ev = reinterpret_cast<REventClassAttr *>(data);
                                                            ^
                                                            )
../src/Cutter.cpp:2449:10: error: ‘R_EVENT_CLASS_ATTR_RENAME’ was not declared in this scope
     case R_EVENT_CLSS_ATTR_RENAME: {
          ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2449:10: note: suggested alternative: ‘R_BIN_CLASS_FRIENDLY’
     case R_EVENT_CLASS_ATTR_RENAME: {
          ^~~~~~~~~~~~~~~~~~~~~~~~~
          R_BIN_CLASS_FRIENDLY
../src/Cutter.cpp:2450:36: error: ‘REventClassAttrRename’ does not name a type
         auto ev = reinterpret_cast<REventClassAttrRename *>(data);
                                    ^~~~~~~~~~~~~~~~~~~~~
../src/Cutter.cpp:2450:58: error: expected ‘>’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassAttrRename *>(data);
                                                          ^
../src/Cutter.cpp:2450:58: error: expected ‘(’ before ‘*’ token
         auto ev = reinterpret_cast<REventClassAttrRename *>(data);
                                                          ^
                                                          (
../src/Cutter.cpp:2450:59: error: expected primary-expression before ‘>’ token
         auto ev = reinterpret_cast<REventClassAttrRename *>(data);
                                                           ^
../src/Cutter.cpp:2450:66: error: expected ‘)’ before ‘;’ token
         auto ev = reinterpret_cast<REventClassAttrRename *>(data);
                                                                  ^
                                                                  )
make: *** [Makefile:2728: Cutter.o] Error 1
```

**To Reproduce**
1. Clone the repository
2. `cd cutter`
3. `mkdir -p build && cd build`
4. `qmake-qt5 ../src/Cutter.pro && make`
5. See error

**Expected behavior**
Expected to compile a binary file.

**Additional context**
Currently working on a fix. I believe this was introduced in #1169.

**Comment by ITAYC0HEN** [comment]
You probably don't have the required version
```
cd cutter/radare2
git pull
cd ..
./build.sh  # although this should pull radare2 as well. But to be sure :)
```

**Comment by ITAYC0HEN** [comment]
This is not an issue with Cutter. When you fix it locally, please close this issue

**Comment by philipmnelson** [comment]
I fixed it. Sorry, I was just confused.
