### ISSUE TITLE
Fix compile on CentOS7 gcc4.8.5

### ISSUE THREAD

**Issue by biyuhao** [radareorg/cutter#2491]
**Environment information**
* Operating System: CentOS7 x86_64
* Cutter version: master branch
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**
compile error on CentOS7 with gcc4.8.5

**To Reproduce**

1. follow the build instruction

**Expected behavior**
build without error

https://stackoverflow.com/questions/30402943/has-cpp-attribute-not-a-function-like-macro
```
cutter/src/core/CutterCommon.h:65:56: error: missing binary operator before token "("
 #if defined(__has_cpp_attribute) && __has_cpp_attribute(deprecated)
                                                        ^
gmake[2]: *** [CMakeFiles/Cutter.dir/Cutter_autogen/mocs_compilation.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Cutter.dir/all] Error 2
gmake: *** [all] Error 2
```
this can be fixed as
```
#if defined(__has_cpp_attribute)
    #if __has_cpp_attribute(deprecated)
        #define DEPRECATED(msg) [[deprecated(msg)]]
    #endif
#else
#define CUTTER_DEPRECATED(msg)
#endif
```

**Screenshots**

**Additional context**

**Comment by karliss** [comment]
If you have the fix please make a pull request.
